Repository coreruleset/coreruleset, pull requests merged in 2021-12, with the labels that each got.

#2193 Refactored and tested version of rule-ctl script
  util/rule_ctl/README.md
  util/rule_ctl/pyproject.toml
  util/rule_ctl/requirements.txt
  util/rule_ctl/rule_ctl.py
  util/rule_ctl/tests/__init__.py
  util/rule_ctl/tests/helpers.py
  util/rule_ctl/tests/rule_ctl_actions_test.py
  util/rule_ctl/tests/rule_ctl_ctl_test.py
  util/rule_ctl/tests/rule_ctl_tags_test.py
  util/rule_ctl/tests/rule_ctl_test.py
  util/rule_ctl/tests/rule_ctl_transformations_test.py
  util/rule_ctl/tests/rule_ctl_variables_test.py
Labels: In progress, Needs action

#2327 fix(path): update path in util to subdirectory
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Labels: cleanup

#2214 Fix 933210 Regex
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
Labels: bug
