Repository coreruleset/coreruleset, pull requests merged in 2022-05, with the labels that each got.

#2558 Bring CONTRIBUTING.MD in line with documentation
  CONTRIBUTING.md
Labels: documentation, ready to merge

#2598 feat(regexp-assemble): Add include preprocessor
  util/regexp-assemble/README.md
  util/regexp-assemble/data/include/.gitkeep
  util/regexp-assemble/lib/context.py
  util/regexp-assemble/lib/operators/assembler.py
  util/regexp-assemble/lib/operators/parser.py
  util/regexp-assemble/lib/operators/updater.py
  util/regexp-assemble/lib/processors/assemble.py
  util/regexp-assemble/lib/processors/include.py
  util/regexp-assemble/lib/processors/processor.py
  util/regexp-assemble/regexp-assemble.py
  util/regexp-assemble/tests/assembler_test.py
  util/regexp-assemble/tests/fixtures.py
  util/regexp-assemble/tests/preprocessor_test.py
Labels: enhancement

#2606 docs: update changelog file to markdown
  CHANGES.md
Labels: documentation

#2531 fix(logging): move audit log part E if there is a chained rule
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
Labels: ready to merge

#2608 fix(docs): fix markdown in changes
  CHANGES.md
Labels: documentation
