Repository coreruleset/coreruleset, pull requests merged in 2022-08, with the labels that each got.

#2594 fix(932130): detect character class unix expressions
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932130.yaml
  util/regexp-assemble/data/932130.data
Labels: bug bounty

#2711 Correct the mode bits on file REQUEST-932...
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Labels: cleanup, ready to merge

#2584 fix(942120): add collate operator
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
  util/regexp-assemble/data/942120.data
Labels: bug bounty

#2708 feat(sqli test): BB testcases for 942521 and 942522 added
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942521.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942522.yaml
Labels: bug bounty

#2705 feat(sqli test): BB testcase for 942120 added
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
Labels: bug bounty

#2706 feat(sqli test): BB testcase for 942520 added
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942520.yaml
Labels: bug bounty

#2702 feat(xss): add js methods to prevent xss
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
Labels: bug bounty

#2714 Add new sqlite test
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942151.yaml
Labels: bug bounty

#2715 fix(test): fix test using old syntax and add go-ftw check
  .github/workflows/go-ftw.yml
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml
Labels: bug, testcase

#2663 feat(list): update php errors list
  rules/php-errors.data
Labels: list update

#2712 Add (de)compression utilities
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/unix-shell.data
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932150.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932160.yaml
  util/regexp-assemble/data/932150.data
Labels: ready to merge, bug bounty

#2727 Add url file 931130
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  tests/regression/tests/REQUEST-931-APPLICATION-ATTACK-RFI/931130.yaml
Labels: ready to merge, bug bounty

#2723 Php wrappers
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933200.yaml
  util/regexp-assemble/data/933200.data
Labels: ready to merge, bug bounty

#2575 fix(sqli): additional sqli auth bypasses
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942180.yaml
  util/regexp-assemble/data/942180.data
Labels: bug bounty

#2729 fix(942130): add glob to sql tautologies
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942130.yaml
  util/regexp-assemble/data/942130.data
Labels: bug bounty

#2718 Detect sqlite_compileoption_get
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942151.yaml
  util/regexp-assemble/data/942151.data
Labels: ready to merge, bug bounty

#2737 fix: properly escape $ in data files
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  util/regexp-assemble/data/932100.data
  util/regexp-assemble/data/932101.data
  util/regexp-assemble/data/932105.data
  util/regexp-assemble/data/932106.data
Labels: bug

#2739 fix: add missing escaping backslash
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  util/regexp-assemble/data/933160.data
Labels: bug

#2740 fix: use correct comments in data file
  util/regexp-assemble/data/932130.data
Labels: bug

#2731 Add more php wrappers
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933200.yaml
  util/regexp-assemble/data/933200.data
Labels: ready to merge, list update

#2581 fix(rce): block PHP function calls without trailing semi-colon (stricter sibling)
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933211.yaml
Labels: bug bounty

#2738 fix: use correct magic prefix
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  util/regexp-assemble/data/932115.data
  util/regexp-assemble/data/932125.data
Labels: bug

#2758 Add archive extensions comment
  crs-setup.conf.example
Labels: ready to merge, bug bounty

#2760 Forbid range header at PL3
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921230.yaml
Labels: bug bounty
