Repository coreruleset/coreruleset, pull requests merged in 2022-09, with the labels that each got.

#2789 chore: remove user-agentt from restricted headers
  CHANGES.md
  crs-setup.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
Labels: cleanup

#2676 fix(932100): update data list
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932100.yaml
  util/regexp-assemble/data/932100.data
Labels: list update

#2572 fix(rfi): additional protocols for RFI rule 931130
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-931-APPLICATION-ATTACK-RFI/931130.yaml
  util/regexp-assemble/data/931130.data
  util/regexp-assemble/data/include/url-schemes.data
Labels: bug bounty

#2806 feat(ci): show logs from containers startup
  .github/workflows/go-ftw.yml
  .github/workflows/test.yml
Labels: enhancement

#2677 fix(932105): update data list
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932105.yaml
  util/regexp-assemble/data/932105.data
Labels: list update

#2805 Remove unnecessary escaping
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
Labels: cleanup, ready to merge

#2810 feat(iis): update iis errors
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/iis-errors.data
  tests/regression/tests/RESPONSE-954-DATA-LEAKAGES-IIS/954120.yaml
Labels: enhancement, list update

#2813 Make rule backreferences consistent and correct
  rules/REQUEST-901-INITIALIZATION.conf
Labels: cleanup, ready to merge

#2801 fix(932210): update sqlite cli commands list
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  util/regexp-assemble/data/932210.data
Labels: list update

#2796 fix(0FA9HCGT): rce alias builtin detection
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932175.yaml
  util/regexp-assemble/data/932175.data
Labels: bug bounty

#2816 fix(sqli): add finding N9FKP2XQ
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932210.yaml
  util/regexp-assemble/data/932210.data
Labels: bug bounty

#2808 fix(sqli): add RKJU2TTV finding
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942530.yaml
Labels: bug bounty

#2798 fix(sqli): add HOH7M88Q-IJ5N1CXB findings
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
  util/regexp-assemble/data/942120.data
Labels: bug bounty

#2821 ci: be less verbose in ftw tests
  .github/workflows/test.yml
Labels: cleanup
