Repository coreruleset/coreruleset, pull requests merged in 2022-10, with the labels that each got.

#2809 fix(OI91S27Z): add local_file scheme from python2
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-931-APPLICATION-ATTACK-RFI/931130.yaml
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml
  util/regexp-assemble/data/include/url-schemes.data
Labels: bug bounty

#2834 ci: fix go-ftw organization change
  .github/workflows/go-ftw.yml
Labels: cleanup

#2831 fix(951240): update rule based on regex
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  util/regexp-assemble/data/951230.data
  util/regexp-assemble/data/951240.data
Labels: cleanup

#2819 fix(935E1D91): add time keyword again
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932100.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932105.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932106.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932110.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932115.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932150.yaml
  util/regexp-assemble/data/932100.data
  util/regexp-assemble/data/932105.data
  util/regexp-assemble/data/932106.data
  util/regexp-assemble/data/932110.data
  util/regexp-assemble/data/932115.data
  util/regexp-assemble/data/932150.data
Labels: bug bounty

#2833 fix: remove reputation variables
  rules/REQUEST-901-INITIALIZATION.conf
Labels: cleanup, ready to merge, complexity: low

#2872 Add sql data conversion ::int and ::bool
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942320.yaml
  util/regexp-assemble/data/942320.data
Labels: sqli-bypass-bathla

#2874 fix(942151): Add sqli functions to rule
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942151.yaml
  util/regexp-assemble/data/942151.data
Labels: sqli-bypass-bathla

#2888 fix(AV6ZO3ZS): change 932100, 932105 and 932150 to ignore case
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932100.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932105.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932150.yaml
  util/regexp-assemble/data/932100.data
  util/regexp-assemble/data/932105.data
  util/regexp-assemble/data/932150.data
Labels: :star: bug bounty

#2893 fix(bb-681L2A1M): add node.js child_process injection
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934100.yaml
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934101.yaml
  util/regexp-assemble/data/934100.data
  util/regexp-assemble/data/934101.data
Labels: :heavy_minus_sign: False Negative - Evasion, :star: bug bounty, :point_right: complexity: medium
