Repository coreruleset/coreruleset, pull requests merged in 2022-06, with the labels that each got.

#2559 fix(942190): Add 'except (select|values)' to auth bypasses
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942340.yaml
  util/regexp-assemble/data/942340.data
Labels: bug bounty

#2556 Add various SQL operators for 942120
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
  util/regexp-assemble/data/942120.data
Labels: bug bounty

#2560 Added sensitive files
  rules/lfi-os-files.data
  rules/restricted-files.data
Labels: bug bounty

#2561 added some php config directives
  rules/php-config-directives.data
Labels: bug bounty

#2563 Added some unix shell
  rules/unix-shell.data
Labels: bug bounty

#2568 942520: Add a new ruleset for SQL Authentication bypass
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942180.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942260.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942340.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942520.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942521.yaml
  util/regexp-assemble/data/942520.data
  util/regexp-assemble/data/942521.data
Labels: bug bounty

#2569 Add entry for c99 and printf utilities (932150)
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932150.yaml
  util/regexp-assemble/data/932150.data
Labels: bug bounty

#2570 Added additional SQL function signatures
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942151.yaml
  util/regexp-assemble/data/942151.data
Labels: bug bounty

#2571 920530: Add a new rule for restricting charset keyword in content type header
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920530.yaml
Labels: bug bounty

#2576 fix (183PG5SJ): Add carriage return (\r) and new line (\n) to regex in rule 941210
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941210.yaml
Labels: bug bounty

#2577 Rules and tests for detecting UNIX shell history invocation
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932330.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932331.yaml
Labels: bug bounty

#2579 nosqli additional operators and fix checks for json body
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942290.yaml
  util/regexp-assemble/data/942290.data
Labels: bug bounty

#2585 933110: Add .phar and .phps to executable php files
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933110.yaml
Labels: bug bounty

#2586 930120: Added ECDSA type SSH identity files
  rules/lfi-os-files.data
Labels: bug bounty

#2588 fix(932110) - added mshta to denylist
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932110.yaml
  util/regexp-assemble/data/932110.data
Labels: bug bounty

#2603 Improved version of #2568
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942520.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942521.yaml
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942522.yaml
  util/regexp-assemble/data/942520.data
  util/regexp-assemble/data/942521.data
Labels: pre-bb-merge

#2624 fix(regexp-assemble): fix complex concatenation
  util/regexp-assemble/lib/processors/assemble.py
  util/regexp-assemble/tests/preprocessor_test.py
Labels: bug, pre-bb-merge

#2538 fix(regexp-assemble): Fix name of data files for 94415x
  util/regexp-assemble/data/944150.data
  util/regexp-assemble/data/944151.data
  util/regexp-assemble/data/944152.data
Labels: pre-bb-merge

#2566 feat(regexp-assemble): Deconstruct magical regexes for 932
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  util/regexp-assemble/data/932100.data
  util/regexp-assemble/data/932101.data
  util/regexp-assemble/data/932105.data
  util/regexp-assemble/data/932106.data
  util/regexp-assemble/data/932110.data
  util/regexp-assemble/data/932115.data
  util/regexp-assemble/data/932150.data
Labels: pre-bb-merge

#2524 add some popular http library & scraping framework
  rules/crawlers-user-agents.data
  rules/scripting-user-agents.data
Labels: pre-bb-merge

#2599 feat(ssrf): move schemes to shared include data
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml
  util/regexp-assemble/data/934120.data
  util/regexp-assemble/data/include/url-schemes.data
Labels: enhancement, pre-bb-merge

#2564 feat(regexp-assemble): Make 951230 work with regexp-assemble
  util/regexp-assemble/data/951230-chain1.data
Labels: pre-bb-merge

#2567 Add functions to cover one half, the not encoded part, of issue 2509
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
  tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941180.yaml
  util/regexp-assemble/data/933160.data
Labels: pre-bb-merge

#2552 932100 932105 add some gtfobins to the blacklist
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932105.yaml
  util/regexp-assemble/data/932100.data
  util/regexp-assemble/data/932105.data
Labels: bug bounty

#2555 fix(ssrf): add octal notation to SSRF dataset 934110
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/ssrf.data
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934120.yaml
Labels: bug bounty

#2662 feat(list): update unix data list
  rules/unix-shell.data
Labels: list update

#2596 fix(933160): php func call evasion fix
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
  util/regexp-assemble/data/932110.data
  util/regexp-assemble/data/933160.data
Labels: bug bounty
