Repository coreruleset/coreruleset, pull requests merged in 2023-07, with the labels that each got.

#3170 feat(windows): update windows commands list
  regex-assembly/932115.ra
  regex-assembly/932370.ra
  regex-assembly/932380.ra
  regex-assembly/exclude/windows-commands-fps.ra
  regex-assembly/include/windows-commands-prefix.ra
  regex-assembly/include/windows-commands.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932380.yaml
Labels: :zap: list update

#3203 fix(934100): improve transformation pipeline
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934100.yaml
Labels: :checkered_flag: ready to merge, :takeout_box: sandbox-ready

#3152 fix: Rework restricted headers
  crs-setup.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920450.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920451.yaml
Labels: :checkered_flag: ready to merge

#3253 feat: backport rule 920620
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920620.yaml
Labels: :arrow_backward: backporting

#3261 docs: update changes
  CHANGES
  CHANGES.md
Labels: :warning: do not merge
