Repository coreruleset/coreruleset, pull requests merged in 2023-12, with the labels that each got.

#3407 fix: solve false positive by shifting ``Field cannot be empty`` to PL2 (953100 PL1, 953101 PL2) (Esad Cetiner)
  rules/php-errors-pl2.data
  rules/php-errors.data
  tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml
  tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
Labels: v4

#3405 feat: added new webshells and tests (955100 PL1) (Jozef Sudolski)
  rules/web-shells-php.data
  tests/regression/tests/RESPONSE-955-WEB-SHELLS/955100.yaml
Labels: v4

#3378 fix: 934130 and 934131 rules
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934130.yaml
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934131.yaml
Labels: v4, :v: v3 Regression Tests

#3417 fix: reword comment (900300 config) (Christian Folini)
  crs-setup.conf.example
Labels: v4

#3395 fix(941390): add missing javascript `prompt` and `confirm` methods
  regex-assembly/941390.ra
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  tests/regression/tests/REQUEST-941-APPLICATION-ATTACK-XSS/941390.yaml
Labels: v4

#3421 chore: changelog updates for 2023-12-13, merged by @dune73
  .changes-pending.md
Labels: changelog-pr

#3423 chore: changelog updates for 2023-12-13, merged by @dune73
  .changes-pending.md
Labels: changelog-pr

#3444 chore: changelog updates for 2023-12-24, merged by @airween
  .changes-pending.md
Labels: changelog-pr
