Repository coreruleset/coreruleset, pull requests merged in 2023-09, with the labels that each got.

#3301 feat: Bring CONTRIBUTING.MD back in line w/ HTML version
  CONTRIBUTING.md
Labels: :book: documentation, :checkered_flag: ready to merge

#3303 fix: Add note of lack of rule range support in ModSecv3
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
Labels: :checkered_flag: ready to merge

#3314 fix: moves FP prone phrase `file size is` to PL2
  rules/php-errors-pl2.data
  rules/php-errors.data
  tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953100.yaml
  tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
Labels: v4

#3320 fix: Fix fps 932260
  regex-assembly/exclude/unix-shell-fps-pl1.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
Labels: :checkered_flag: ready to merge, v4
