Repository coreruleset/coreruleset, pull requests merged in 2024-12, with the labels that each got.

#3965 feat: prevent accessing PHP variables
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933135.yaml
Labels: release:new-detection

#3967 chore: release v4.10.0
  CHANGES.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release

#3968 chore: post-release v4.11.0-dev
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: post-release, release:ignore

#3970 feat: release yaml support for new label release:remove-rules
  .github/release.yml
Labels: release:ignore

#3969 feat: Remove rules for lack of viable attack scenario (920220 PL1, 920221 PL1)
  regex-assembly/920220-chain1.ra
  regex-assembly/920221.ra
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920220.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920221.yaml
Labels: release:remove-rules

#3971 fix: remove aliases man, mi, si and resolve positives (932125 PL1)
  regex-assembly/932125.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932125.yaml
Labels: release:fix
