Repository coreruleset/coreruleset, pull requests merged in 2024-08, with the labels that each got.

#3784 fix: update ``docker-compose`` to ``docker compose``
  .github/workflows/test.yml
Labels: release:ignore

#3790 docs: improve documentationt of 941160
  .github/workflows/lint.yaml
  regex-assembly/941160.ra
  util/crs-rules-check/rules-check.py
Labels: release:ignore

#3794 fix: tests typos
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920430.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
Labels: release:ignore

#3798 ci: fix docker compose call
  .github/workflows/test.yml
  tests/docker-compose.yml
Labels: release:ignore, :wrench: ci/cd

#3782 fix(942160): check REQUEST_FILENAME
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942160.yaml
Labels: release:fix

#3799 fix: prevent using backslash in file names
  regex-assembly/920120.ra
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920121.yaml
Labels: release:important

#3800 fix: prevent using backslash in file names (v3)
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920121.yaml
Labels: :arrow_backward: backporting, release:ignore

#3796 feat: add new rule to catch invalid character in multipart headers
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
Labels: release:important

#3801 test: enable disabled 920480 tests
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920480.yaml
Labels: :test_tube: testcase, release:ignore

#3797 feat: add new rule to catch invalid character in multipart headers (v3)
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
Labels: :arrow_backward: backporting, release:ignore

#3805 fix: update supported versions
  SECURITY.md
Labels: release:ignore

#3806 Release/v3.3.6
  .github/workflows/test.yml
  CHANGES.md
  CONTRIBUTORS.md
  README.md
  SPONSORS.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
  rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
  rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
  rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
  rules/REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf
  rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-910-IP-REPUTATION.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-912-DOS-PROTECTION.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
  tests/docker-compose.yml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920120.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920121.yaml
  tests/regression/tests/REQUEST-922-MULTIPART-ATTACK/922130.yaml
Labels: :rocket: release

#3807 chore: merge back after 3.3.6 release
  CHANGES.md
  CONTRIBUTORS.md
  README.md
  SPONSORS.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
  rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
  rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
  rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
  rules/REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf
  rules/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-910-IP-REPUTATION.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-912-DOS-PROTECTION.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: post-release
