Repository coreruleset/coreruleset, pull requests merged in 2024-02, with the labels that each got.

#3536 docs: fix changelog entries
  CHANGES.md
Labels: v4, v4-doc

#3540 docs: Update and tidy CHANGES.md file for v4.0 release
  CHANGES.md
Labels: :timer_clock: In progress, :broom: cleanup, :warning: do not merge, v4, v4-doc

#3549 docs: clean changes pending, everything move into CHANGES via PR 3548
  .changes-pending.md
Labels: v4, v4-doc

#3555 docs: remove sponsor F5 / VMWare
  SPONSORS.md
Labels: v4, v4-doc

#3559 feat: remove SecCollectionTimeout from crs-setup.conf
  crs-setup.conf.example
Labels: v4

#3566 docs: update INSTALL to cover CRS4
  INSTALL
  INSTALL.md
Labels: v4-doc

#3548 docs: final changes to CHANGES.md before v4
  .changes-pending.md
  CHANGES.md
Labels: v4, v4-doc
