Repository coreruleset/coreruleset, pull requests merged in 2024-11, with the labels that each got.

#3920 fix: do not run scheduled in forked repos
  .github/workflows/nightly.yml
Labels: release:ignore

#3924 feat: add quantitative testing to Git workflow
  .github/workflows/quantitative.yaml
Labels: release:new-feature

#3927 chore: quantitative diff
  .github/workflows/quantitative.yaml
Labels: release:ignore, :wrench: ci/cd

#3946 chore: update ftw release
  .github/workflows/quantitative.yaml
  .github/workflows/test.yml
Labels: release:ignore

#3947 chore: release v4.9.0
  CHANGES.md
  CONTRIBUTORS.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release

#3948 chore: post-release v4.10.0-dev
  CHANGES.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: release:ignore

#3949 chore: update leaders
  CONTRIBUTORS.md
Labels: release:ignore
