Repository coreruleset/coreruleset, pull requests merged in 2024-10, with the labels that each got.

#3847 fix: old test schema field in 932239.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
Labels: release:ignore

#3851 fix: add missing "log:" to 932239
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
Labels: release:ignore

#3855 fix: invalid rule_id in test
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933110.yaml
Labels: release:ignore

#3832 ci: do not run pipeline twice
  .editorconfig
  .github/ISSUE_TEMPLATE/04_feature.md
  .github/release.yml
  .github/workflows/lint.yaml
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  docs/README.md
  rules/java-classes.data
  tests/regression/CRS_Tests.py
  util/php-dictionary-gen/php-dictionary-creator.sh
  util/regexp-tricks/negative-lookahead.py
Labels: release:ignore, :wrench: ci/cd

#3854 fix: remove duplicate test for 920270
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920270.yaml
Labels: release:ignore

#3841 fix(942120): update operators
  regex-assembly/942120.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942120.yaml
Labels: release:fix

#3863 fix(933120): do not match on base64 encoded strings
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
Labels: release:fix

#3862 fix(refactor): 942130 and 942131 regex-assembly
  regex-assembly/942130.ra
  regex-assembly/942131.ra
Labels: release:refactor, refactoring

#3865 feat: Shorten Tests for 920400-1
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920400.yaml
Labels: release:ignore

#3845 fix(942520): SQL operators can be one or more characters
  regex-assembly/942520.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Labels: release:fix

#3885 chore: remove verify id-range
  util/id-range
  util/verify.rb
Labels: release:refactor

#3891 chore: remove find-max-datalen-in-tests
  util/find-max-datalen-in-tests/README.md
  util/find-max-datalen-in-tests/find_max_datalen.py
Labels: release:refactor

#3883 chore: remove honeypot sensor
  util/honeypot-sensor/README.md
  util/honeypot-sensor/mlogc-honeypot-sensor.conf
  util/honeypot-sensor/modsecurity_crs_10_honeypot.conf
Labels: release:refactor

#3887 chore: remove browser tools
  util/browser-tools/js-overrides.js
Labels: release:refactor

#3879 chore: remove send-payload-pls
  util/send-payload-pls.sh
Labels: release:refactor

#3875 chore: remove geo-location
  util/geo-location/README
Labels: release:refactor

#3873 chore: remove crs2 renumbering
  util/crs2-renumbering/IdNumbering.csv
  util/crs2-renumbering/README
  util/crs2-renumbering/update.py
Labels: release:refactor

#3869 chore: remove change-version script
  util/change-version/README.md
  util/change-version/README.txt
  util/change-version/change-version.py
Labels: release:refactor

#3877 chore: remove join multiline rules
  util/join-multiline-rules/join.py
Labels: release:refactor

#3871 chore: remove av-scanning
  util/av-scanning/runAV/common.c
  util/av-scanning/runAV/common.h
  util/av-scanning/runAV/comp
  util/av-scanning/runAV/runAV-clamd.c
  util/av-scanning/runAV/runAV.c
  util/av-scanning/runav.pl
Labels: release:refactor

#3889 chore: remove util virtual patching
  util/virtual-patching/arachni2modsec.pl
  util/virtual-patching/zap2modsec.pl
Labels: release:refactor

#3894 fix: bypass by supplying whitespace or path argument (933120 PL-1)
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
Labels: :heavy_minus_sign: False Negative - Evasion, release:ignore

#3893 chore: remove fp-finder
  util/fp-finder/english-extended.txt
  util/fp-finder/spell.sh
Labels: release:refactor

#3904 docs: update README
  README.md
Labels: release:ignore

#3908 fix(ci): get version when releasing from branch name
  .github/workflows/lint.yaml
Labels: release:ignore

#3907 chore: release v4.8.0
  CHANGES.md
  CONTRIBUTORS.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: release:ignore

#3906 fix: 9EA-241022 v3
  crs-setup.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920420.yaml
  tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920470.yaml
Labels: :bug: bug, :arrow_backward: backporting, release:important
