Repository coreruleset/coreruleset, pull requests merged in 2025-08, with the labels that each got.

#4225 chore: release v4.17.1
  CHANGES.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-956-DATA-LEAKAGES-RUBY.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release, release:ignore

#4237 fix: nginx test-override typo
  tests/regression/nginx-overrides.yaml
Labels: release:ignore

#4234 fix(942370): remove dot star
  regex-assembly/942370.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Labels: release:fix

#4224 fix: avoid matching non-ruby errors and source code
  rules/RESPONSE-956-DATA-LEAKAGES-RUBY.conf
  rules/ruby-errors.data
  tests/regression/tests/RESPONSE-956-DATA-LEAKAGES-RUBY/956100.yaml
  tests/regression/tests/RESPONSE-956-DATA-LEAKAGES-RUBY/956110.yaml
Labels: release:fix

#3881 chore: find rules without test
  .github/workflows/lint.yaml
  tests/TESTS_EXCLUSIONS
  util/find-rules-without-test/README.md
  util/find-rules-without-test/find-rules-without-test.py
  util/find-rules-without-test/requirements.txt
Labels: release:refactor
