Repository coreruleset/coreruleset, pull requests merged in 2025-09, with the labels that each got.

#4253 fix: eliminate the effect of backquote character in linter workflow
  .github/workflows/lint.yaml
Labels: release:ignore

#4254 chore: release v4.18.0
  CHANGES.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-956-DATA-LEAKAGES-RUBY.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release, release:ignore

#4255 chore: post-release v4.19.0-dev
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-956-DATA-LEAKAGES-RUBY.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: release:ignore

#4256 fix: update linter and fix commit message passing
  .github/workflows/lint.yaml
Labels: release:ignore

#4257 fix(953100): remove generic SQLSTATE error codes causing false positives
  rules/php-errors.data
Labels: release:fix

#3767 fix(942550): cleanup regex
  regex-assembly/942550.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942550.yaml
Labels: :mage: regex-assembly

#4266 fix: duplicate in sql-errors.data
  rules/sql-errors.data
Labels: release:ignore

#4272 fix: reduce false positives with php response rules
  regex-assembly/953101.ra
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/php-errors-pl2.data
  rules/php-errors.data
  tests/regression/tests/RESPONSE-953-DATA-LEAKAGES-PHP/953101.yaml
Labels: release:fix
