Repository coreruleset/coreruleset, pull requests merged in 2025-05, with the labels that each got.

#4105 fix: false positive with `title_strip_tags` by moving `strip_tags` to 933160
  regex-assembly/933160.ra
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/php-function-names-933150.data
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
Labels: release:fix

#4084 chore: improve new issue form
  .github/ISSUE_TEMPLATE/new_issue.yaml
Labels: release:ignore

#4111 fix: remove `self` command
  regex-assembly/exclude/unix-shell-fps-pl1.ra
  regex-assembly/include/unix-shell-4andup.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932236.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
Labels: release:fix

#4115 feat: add User-Agent and Referer into targets (942280 PL1)
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  tests/regression/tests/REQUEST-942-APPLICATION-ATTACK-SQLI/942280.yaml
Labels: release:new-detection

#4122 chore: update crs-linter
  .github/workflows/lint.yaml
Labels: release:ignore

#4080 feat: update `java-classes.data`
  rules/java-classes.data
Labels: release:new-detection

#4130 feat: block database yaml files
  rules/lfi-os-files.data
  rules/restricted-files.data
  rules/restricted-upload.data
Labels: release:new-detection

#4135 feat: remove unnecessary character class from 933151
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
Labels: release:refactor

#4142 fix: false positives with session tokens/cookies 933150
  regex-assembly/933160.ra
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/php-function-names-933150.data
Labels: release:fix

#4141 fix: add word ending to unix command sendmail (932235 PL1, 932236 PL2, 932239 PL2, 932260 PL1)
  regex-assembly/include/unix-shell-4andup.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
Labels: release:fix

#4138 feat: 933120 change from capture and double `pmf` to regex
  regex-assembly/933120.ra
  regex-assembly/include/php-config-directives.ra
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933120.yaml
Labels: release:refactor
