Repository coreruleset/coreruleset, pull requests merged in 2025-02, with the labels that each got.

#3735 fix: prevent invalid commands matches on 5 characters or less (932220 PL-2, 932230 PL-1, 932232 PL-3, 932235 PL-1, 932236 PL-2, 932237 PL-3, 932238 PL-3, 932239 PL-2, 932250 PL-1, 932260 PL-1)
  regex-assembly/932235.ra
  regex-assembly/932236.ra
  regex-assembly/932237.ra
  regex-assembly/932239.ra
  regex-assembly/932250.ra
  regex-assembly/932260.ra
  regex-assembly/exclude/unix-shell-fps-pl1.ra
  regex-assembly/exclude/unix-shell-fps-pl2.ra
  regex-assembly/include/unix-shell-4andup.ra
  regex-assembly/include/unix-shell-pl3.ra
  regex-assembly/include/unix-shell-upto3.ra
  regex-assembly/toolchain.yaml
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/unix-shell.data
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932220.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932230.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932232.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932235.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932236.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932237.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932239.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932250.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932260.yaml
Labels: :heavy_plus_sign: False Positive

#4003 docs: add warning about default charsets modification
  crs-setup.conf.example
Labels: :book: documentation

#4004 chore: move rule_ctl to its own repo
  util/rule_ctl/README.md
  util/rule_ctl/pyproject.toml
  util/rule_ctl/requirements.txt
  util/rule_ctl/rule_ctl.py
  util/rule_ctl/tests/__init__.py
  util/rule_ctl/tests/helpers.py
  util/rule_ctl/tests/rule_ctl_actions_test.py
  util/rule_ctl/tests/rule_ctl_ctl_test.py
  util/rule_ctl/tests/rule_ctl_tags_test.py
  util/rule_ctl/tests/rule_ctl_test.py
  util/rule_ctl/tests/rule_ctl_transformations_test.py
  util/rule_ctl/tests/rule_ctl_variables_test.py
Labels: release:ignore

#4007 fix: add argument name to function call
  util/crs-rules-check/rules-check.py
Labels: release:ignore

#4009 fix: fix response splitting rules and tests
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  tests/regression/tests/REQUEST-921-PROTOCOL-ATTACK/921140.yaml
Labels: release:fix

#4008 chore: add debug versions for quick local testing
  tests/docker-compose.yml
Labels: release:ignore

#4010 fix(933160): use better regex
  regex-assembly/933160.ra
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
Labels: release:fix

#4016 fix: move fopen to 933160 to resolve fp with `RootAndLeafOpenCamera.jpg` (933150 PL-1, 933160 PL-1)
  regex-assembly/933160.ra
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/php-function-names-933150.data
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933150.yaml
  tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933160.yaml
Labels: release:fix
