Repository coreruleset/coreruleset, pull requests merged in 2025-06, with the labels that each got.

#4156 chore: release v4.15.0
  CHANGES.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: release:ignore

#4145 feat: remediation for Python SSTI
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  tests/regression/tests/REQUEST-934-APPLICATION-ATTACK-GENERIC/934180.yaml
  util/APPROVED_TAGS
Labels: release:new-detection

#4165 fix(934140): remove dot star
  regex-assembly/934140.ra
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
Labels: :mage: regex-assembly, release:fix

#4166 fix(932370): remove dot star
  regex-assembly/include/windows-commands-prefix.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Labels: :mage: regex-assembly, release:fix

#4169 fix(955xxx): remove dot star
  rules/RESPONSE-955-WEB-SHELLS.conf
Labels: :mage: regex-assembly, release:fix

#4102 feat: detect generic config filenames
  rules/lfi-os-files.data
  rules/restricted-files.data
  rules/restricted-upload.data
Labels: release:new-detection

#4015 fix: create a stricter sibling to 932370 and move `at` to PL-2 (932370 PL-1, 932371 PL-2)
  regex-assembly/932370.ra
  regex-assembly/932371.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932370.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932371.yaml
Labels: release:fix

#4164 fix(942340): remove dot star
  regex-assembly/942180.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Labels: :mage: regex-assembly, release:fix

#3780 feat: added rule to detect Bash Brace Expansion
  regex-assembly/932280.ra
  regex-assembly/932281.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932280.yaml
  tests/regression/tests/REQUEST-932-APPLICATION-ATTACK-RCE/932281.yaml
Labels: release:new-detection

#4162 feat: added MongoDB operators
  regex-assembly/942290.ra
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
Labels: release:new-detection

#4143 feat: added zmodload and sudo-rs
  regex-assembly/include/unix-shell-4andup.ra
  regex-assembly/include/unix-shell-upto3.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/unix-shell-builtins.data
  rules/unix-shell.data
Labels: release:new-detection

#4175 chore: release v4.16.0
  CHANGES.md
  CONTRIBUTORS.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release, release:ignore
