Repository coreruleset/coreruleset, pull requests merged in 2025-01, with the labels that each got.

#3974 chore: update go-ftw and secrules_parsing versions
  .github/workflows/lint.yaml
  .github/workflows/quantitative.yaml
  .github/workflows/test.yml
Labels: release:ignore

#3977 fix: make 932300 actually case-insensitive
  regex-assembly/932300.ra
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
Labels: release:fix

#3984 chore: remove unused negative lookahead script
  util/regexp-tricks/negative-lookahead.py
Labels: release:ignore

#3986 chore: release 4.11.0
  CHANGES.md
  SECURITY.md
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: :rocket: release, release:ignore

#3987 chore: post-release v4.12.0-dev
  crs-setup.conf.example
  rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  rules/REQUEST-901-INITIALIZATION.conf
  rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  rules/REQUEST-913-SCANNER-DETECTION.conf
  rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  rules/REQUEST-921-PROTOCOL-ATTACK.conf
  rules/REQUEST-922-MULTIPART-ATTACK.conf
  rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  rules/REQUEST-949-BLOCKING-EVALUATION.conf
  rules/RESPONSE-950-DATA-LEAKAGES.conf
  rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  rules/RESPONSE-955-WEB-SHELLS.conf
  rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  rules/RESPONSE-980-CORRELATION.conf
  rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
Labels: release:ignore
